---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: maxrainer
    - COLLECTION_NAME: network_demo
  matrix:
    - DISTRO: centos7
      PYTHON_INTERPRETER: /usr/bin/python


install:
  # Install Ansible.
  - pip install ansible


before_script:
  # Move the collection into the required path to make ansible-test work.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Run tests.
  - ansible-test integration --docker geerlingguy/docker-$DISTRO-ansible:latest --python-interpreter $PYTHON_INTERPRETER

deploy:
  provider: script
  script: ansible-playbook -i 'localhost,' scripts/deploy.yml -e "tag=$TRAVIS_TAG"
  'on':
    tags: true
    condition: $DISTRO = centos7